In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
1. Scalar & Array Operations (Redo Section with Your Own Values):
Run the given code with scalar = 3.7 and a new array of at least 6 elements.

Show outputs of all built-in mathematical functions (sin, cos, tan, etc.).

scaler = 3.7
array = np.array([5, 6, 9, 8, 10, 7, 4])

# Trigonometric functions
sin_values = np.sin(array)
cos_values = np.cos(array)
tan_values = np.tan(array)
asin_values = np.arcsin(np.clip(array / np.max(array), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(array / np.max(array), -1, 1))
atan_values = np.arctan(array)

# Display results
print("Resul of Sin:", sin_values)
print("Resul of Cos:", cos_values)
print("Resul of Tan:", tan_values)
print("Resul of asin:", asin_values)
print("Resul of acos:", acos_values)
print("Resul of atan:", atan_values)

NameError: name 'np' is not defined

In [ ]:
Apply the Same Operations on a 3×2 Matrix
Create a 3×2 matrix with custom values.

Perform and display results of:

Trigonometric functions

Exponential & logarithmic functions

Absolute value & square root

Remainder when divided by 2

Rounding (round, floor, ceil)

# Creating a 3x2 matrix
matrix = np.array([[10, 2,], [42, 34], [59, 60]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[10  2]
 [42 34]
 [59 60]]

sin:
 [[-0.54402111  0.90929743]
 [-0.91652155  0.52908269]
 [ 0.63673801 -0.30481062]]

cos:
 [[-0.83907153 -0.41614684]
 [-0.39998531 -0.84857027]
 [-0.77108022 -0.95241298]]

tan:
 [[ 0.64836083 -2.18503986]
 [ 2.29138799 -0.62349896]
 [-0.82577401  0.32004039]]

asine:
 [[0.16744808 0.03333951]
 [0.7753975  0.60245463]
 [1.38796761 1.57079633]]

acosine:
 [[1.40334825 1.53745682]
 [0.79539883 0.96834169]
 [0.18282872 0.        ]]

atangent:
 [[1.47112767 1.10714872]
 [1.5469913  1.54139304]
 [1.5538488  1.5541312 ]]

exp:
 [[2.20264658e+04 7.38905610e+00]
 [1.73927494e+18 5.83461743e+14]
 [4.20121040e+25 1.14200739e+26]]

log (natural):
 [[2.30258509 0.69314718]
 [3.73766962 3.52636052]
 [4.07753744 4.09434456]]

abs:
 [[10  2]
 [42 34]
 [59 60]]

sqrt:
 [[3.16227766 1.41421356]
 [6.4807407  5.83095189]
 [7.68114575 7.74596669]]

rem (remainder when divided by 2):
 [[0 0]
 [0 0]
 [1 0]]

round:
 [[10  2]
 [42 34]
 [59 60]]

floor:
 [[10.  2.]
 

In [ ]:
Perform Same Operations on a 2×3 Matrix
Your 2×3 matrix can have float values (e.g., 2.1, 4.7…).

Implement and display:

Max & Min (with indices)

Vector length

Sorted version (both row-wise descending and entire matrix descending)

Sum, Product

Median, Mean, Standard Deviation

# Sample vector 2x3 matrix
vec = np.array([[3.3, 1.2, 4.6], [1.9, 5.2, 9.7]])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)


# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)

Max value: 9.7 at index 5
Min value: 1.2 at index 1
Length of vector: 2
Sorted vector: [[1.2 3.3 4.6]
 [1.9 5.2 9.7]]
Sum of elements: 25.9
Product of elements: 1745.7485759999995
Median value: 3.9499999999999997
Mean value: 4.316666666666666
Standard deviation: 2.781736068636914
